### ISSUE TITLE
Widget Field - style broken with select field

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#175]
Step to reproduce:
1. Create a "Numeric" field by giving name "Grade 1 Student Male" and mark as custom widget field
2. Save that Layer
3. Edit the layer above -> create a widget field
4. In Select field to add to widget table cell doesn't have "+" button to display for user to add but click on that area work

Expected: it should display "+" button next to combo box select field to add field into widget table cell
<img width="468" alt="widget_field_broken_style" src="https://user-images.githubusercontent.com/745429/34553001-9eecbc1c-f157-11e7-8218-45331a6cf348.png">

**Comment by Thyda-Eng** [comment]
Cannot reproduce.
