### ISSUE TITLE
Unexpected Error when create site that reached alert with date criteria and email

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#180]
As a collection owner
When I create an alert threshold with 
   1. date field less than 1/1/2018
   2. email field equal 'test@abc.com'
Then user can't submit offline site that reached this alert
And there is nothing happen to let user know on the submission window

**Comment by Thyda-Eng** [comment]
It is fixed with #179 , I cannot reproduce it anymore.
