### ISSUE TITLE
Critical-Single mode edit has unexpected error

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#46]
Add one more layer to my existing collection
Then edit an existing site with previous layer scheme -> unexpected error
![single_mode_edit](https://cloud.githubusercontent.com/assets/745429/19882083/82f736c0-a03d-11e6-8fa2-00619a921f4a.png)

**Comment by Thyda-Eng** [comment]
Because you have change the config on the field, and yes it should show the the error message rather than unexpected error.
