### ISSUE TITLE
Critical-Can't edit skip logic

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#48]
1. Create a field with skip logic with select field, condition and leave value blank
2. Save layer
3. Edit that field again but skip logic didn't allow to edit
![skip_logic_cannot_edit](https://cloud.githubusercontent.com/assets/745429/19882554/17acbdaa-a041-11e6-94a1-47511a3c291f.png)

**Comment by sokmesakhiev** [comment]
This UI is not for edit and to edit, please click on edit button at the bottom
