### ISSUE TITLE
Critical-Skip logic and custom validation should be not bind

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#50]
1. Create a numeric field
2. Enable skip logic and custom validation and modified field condition one of those 2 then it will change both of them(bind)
![skip_logic_and_custom_validation_problem](https://cloud.githubusercontent.com/assets/745429/19882918/ae17ddc2-a043-11e6-9761-e0a0d473cb94.png)

**Comment by sokmesakhiev** [comment]
Problem binding and view UI is same to edit UI
