### ISSUE TITLE
Critical-Report query problem when dependencies fields was removed

### ISSUE THREAD

**Issue by kakada** [ilabsea/resourcemap-program-assessment#59]
1. Create a number field A in layer 1
2. Build a report query with numeric field A
3. Remove field A in layer 1
4. Click edit on the report query just created then nothing happen -> it should display message information to user in order to make user known what went wrong

**Comment by Thyda-Eng** [comment]
should restrict delete field if the field link to report query

**Comment by kakada** [comment]
work as expected
